<a href="https://colab.research.google.com/github/Aprilianiput21/TA_Model-ETp/blob/main/Outlier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Outlier

In [49]:
#Import Library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [50]:
#Reading Dataset dalam format data Excel
df_1 = pd.read_excel('/content/Tungkub_Hourly_PM_New.xlsx')
df_1 = df_1.drop(0)
df_1 = df_1.drop(1)
df_1.head()

,Date,Year,DOY,Time,T,RH,U,Rs,Dec,dr,...,ρ Cp,ra,G,rc,LE,LE.1,ET,Unnamed: 28,Unnamed: 29,Unnamed: 30
2,2023-02-13 12:00:02,2023,44,12,29.312,70.219,1,438.1,-0.23786,1.023978,...,1256.791534,193.254701,33.560402,69,247.677118,0.891638,0.363934,h,0.12,m
3,2023-02-13 13:00:02,2023,44,13,29.676,69.697,1.67,375.6,-0.23786,1.023978,...,1252.71032,115.721378,28.75582,69,221.856096,0.798682,0.325993,rc day,69.00,s/m
4,2023-02-13 14:00:02,2023,44,14,28.11,78.695,1.34,323.1,-0.23786,1.023978,...,1249.075848,144.219926,24.783312,69,179.470678,0.646094,0.263712,rc night,690.00,s/m
5,2023-02-13 15:00:02,2023,44,15,26.588,76.712,1,214.4,-0.23786,1.023978,...,1242.151358,193.254701,16.314088,69,120.980315,0.435529,0.177767,Latitude,-8.00,degrees
6,2023-02-13 16:00:02,2023,44,16,27.767,76.011,0.67,210.6,-0.23786,1.023978,...,1239.162128,288.439852,16.06366,69,119.166415,0.428999,0.175102,Longitude,115.00,degrees

In [51]:
# Menghitung IQR
Q1 = df_1['Rs'].quantile(0.25)
Q3 = df_1['Rs'].quantile(0.75)
IQR = Q3 - Q1

# Menentukan batas bawah dan batas atas
batas_bawah = Q1 - 1.5 * IQR
batas_atas = Q3 + 1.5 * IQR

# Menandai outlier
df_1['outlier_Rs'] = (df_1['Rs'] < batas_bawah) | (df_1['Rs'] > batas_atas)


print(df_1['outlier_Rs'])

2       False
3       False
4       False
5       False
6       False
        ...
5558    False
5559    False
5560    False
5561    False
5562    False
Name: outlier_Rs, Length: 5561, dtype: bool

In [52]:
# Menghitung IQR
Q1 = df_1['T'].quantile(0.25)
Q3 = df_1['T'].quantile(0.75)
IQR = Q3 - Q1

# Menentukan batas bawah dan batas atas
batas_bawah = Q1 - 1.5 * IQR
batas_atas = Q3 + 1.5 * IQR

# Menandai outlier
df_1['outlier_T'] = (df_1['T'] < batas_bawah) | (df_1['T'] > batas_atas)


print(df_1['outlier_T'])

2       False
3       False
4       False
5       False
6       False
        ...
5558    False
5559    False
5560    False
5561    False
5562    False
Name: outlier_T, Length: 5561, dtype: bool

In [53]:
#Menghitung IQR
Q1 = df_1['RH'].quantile(0.25)
Q3 = df_1['RH'].quantile(0.75)
IQR = Q3 - Q1

# Menentukan batas bawah dan batas atas
batas_bawah = Q1 - 1.5 * IQR
batas_atas = Q3 + 1.5 * IQR

# Menandai outlier
df_1['outlier_RH'] = (df_1['RH'] < batas_bawah) | (df_1['RH'] > batas_atas)


print(df_1['outlier_RH'])

2       False
3       False
4       False
5       False
6       False
        ...
5558    False
5559    False
5560    False
5561    False
5562    False
Name: outlier_RH, Length: 5561, dtype: bool

In [54]:
#Reading Dataset dalam format data Excel
df_2 = pd.read_excel('/content/Tungkub_Hourly_PM_New.xlsx')
df_2 = df_2.drop(0)
df_2 = df_2.drop(1)
df_2.head()

,Date,Year,DOY,Time,T,RH,U,Rs,Dec,dr,...,ρ Cp,ra,G,rc,LE,LE.1,ET,Unnamed: 28,Unnamed: 29,Unnamed: 30
2,2023-02-13 12:00:02,2023,44,12,29.312,70.219,1,438.1,-0.23786,1.023978,...,1256.791534,193.254701,33.560402,69,247.677118,0.891638,0.363934,h,0.12,m
3,2023-02-13 13:00:02,2023,44,13,29.676,69.697,1.67,375.6,-0.23786,1.023978,...,1252.71032,115.721378,28.75582,69,221.856096,0.798682,0.325993,rc day,69.00,s/m
4,2023-02-13 14:00:02,2023,44,14,28.11,78.695,1.34,323.1,-0.23786,1.023978,...,1249.075848,144.219926,24.783312,69,179.470678,0.646094,0.263712,rc night,690.00,s/m
5,2023-02-13 15:00:02,2023,44,15,26.588,76.712,1,214.4,-0.23786,1.023978,...,1242.151358,193.254701,16.314088,69,120.980315,0.435529,0.177767,Latitude,-8.00,degrees
6,2023-02-13 16:00:02,2023,44,16,27.767,76.011,0.67,210.6,-0.23786,1.023978,...,1239.162128,288.439852,16.06366,69,119.166415,0.428999,0.175102,Longitude,115.00,degrees

In [55]:
#Menghitung IQR
Q1 = df_2['Rs'].quantile(0.25)
Q3 = df_2['Rs'].quantile(0.75)
IQR = Q3 - Q1

# Menentukan batas bawah dan batas atas
batas_bawah = Q1 - 1.5 * IQR
batas_atas = Q3 + 1.5 * IQR

# Menandai outlier
df_2['outlier_Rs'] = (df_2['Rs'] < batas_bawah) | (df_2['Rs'] > batas_atas)


print(df_2['outlier_Rs'])

2       False
3       False
4       False
5       False
6       False
        ...
5558    False
5559    False
5560    False
5561    False
5562    False
Name: outlier_Rs, Length: 5561, dtype: bool

In [56]:
#Menghitung IQR
Q1 = df_2['T'].quantile(0.25)
Q3 = df_2['T'].quantile(0.75)
IQR = Q3 - Q1

# Menentukan batas bawah dan batas atas
batas_bawah = Q1 - 1.5 * IQR
batas_atas = Q3 + 1.5 * IQR

# Menandai outlier
df_2['outlier_T'] = (df_2['T'] < batas_bawah) | (df_2['T'] > batas_atas)


print(df_2['outlier_T'])

2       False
3       False
4       False
5       False
6       False
        ...
5558    False
5559    False
5560    False
5561    False
5562    False
Name: outlier_T, Length: 5561, dtype: bool

In [57]:
#Menghitung IQR
Q1 = df_2['RH'].quantile(0.25)
Q3 = df_2['RH'].quantile(0.75)
IQR = Q3 - Q1

# Menentukan batas bawah dan batas atas
batas_bawah = Q1 - 1.5 * IQR
batas_atas = Q3 + 1.5 * IQR

# Menandai outlier
df_2['outlier_RH'] = (df_2['RH'] < batas_bawah) | (df_2['RH'] > batas_atas)


print(df_2['outlier_RH'])

2       False
3       False
4       False
5       False
6       False
        ...
5558    False
5559    False
5560    False
5561    False
5562    False
Name: outlier_RH, Length: 5561, dtype: bool